annealing_parameters:
  max_iter: 100
  minimizer_kwargs:
    options:
      disp: true
      maxiter: 5
    tol: 0.01
  n_consecutive_exception_max: null
  no_local_search: true
  temperature: 1
decomposition_parameters:
  file:
  - config/examples/decomposition_parameters.yaml
run_parameters:
  continue_annealing: true
  debug: true
  input_folder: null
  output_folder: example/optimization
  save: true
  save_all_iterations: false
  verbosity: debug
  n_processors: 1
search_parameters:
  loss_function: closure
  individual_search: false
  na_penalty: 0
  parameters_to_search:
  - wing_loading
  search_limits:
    CD:
    - 0.05
    - 0.15
    CL:
    - 1.2
    - 1.8
    mass:
    - 3.5
    wing_area:
    - 0.25
    - 1.4
    wing_loading:
    - 4
    - 8
